<a href="https://colab.research.google.com/github/mayamoneib/deliveryfood/blob/main/deliverydummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#%matplotlib inline
#plt.style.use("seaborn")
#when using colab
# Set the style for plots using the updated seaborn style
plt.style.use("seaborn-v0_8") # Changed from 'seaborn' to 'seaborn-v0_8'

df = pd.read_csv('onlinedeliverydata.csv')

In [ ]:
df_copy = df.copy()
df_copy.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  ...  \
0              Post Graduate            4   12.9766    77.5993    560001  ...   
1                   Graduate            3   12.9770    77.5773    560009  ...   
2              Post Graduate            3   12.9551    77.6593    560017  ...   
3                   Graduate            6   12.9473    77.5616    560019  ...   
4              Post Graduate            4   12.9850    77.5533    560010  ...   

     Less Delivery time High Quality of package       Number of calls  \
0  Moderately Important    Moderately Important  Moderately Important   
1        Very Important          Very Important        Very Important   
2             Important          Very Important  Moderately Important   
3        Very Important               Important  Moderately Important   
4             Important               Important  Moderately Important   

             Politeness            Freshness            Temperature  \
0  Moderately Important  Moderately Important  Moderately Important   
1        Very Important        Very Important        Very Important   
2        Very Important        Very Important             Important   
3        Very Important        Very Important        Very Important   
4             Important             Important             Important   

            Good Taste          Good Quantity Output  \
0  Moderately Important  Moderately Important    Yes   
1        Very Important        Very Important    Yes   
2        Very Important  Moderately Important    Yes   
3        Very Important             Important    Yes   
4        Very Important        Very Important    Yes   

                                             Reviews  
0                                              Nil\n  
1                                                Nil  
2  Many a times payment gateways are an issue, so...  
3                                                nil  
4                                                NIL  

[5 rows x 55 columns]

In [ ]:
df_copy.drop(['latitude', 'longitude', 'Pin code','Reviews', 'Monthly Income', 'Educational Qualifications',
              'Family size', 'Medium (P1)', 'Medium (P2)', 'Meal(P2)', 'Perference(P1)', 'Perference(P2)',
              'Health Concern', 'Bad past experience', 'Delay of delivery person picking up food', 'Google Maps Accuracy',
              'Good Road Condition', 'Low quantity low time', 'Delivery person ability', 'Number of calls'], axis=1, inplace=True)

In [ ]:
# Define the order of categories
ordered_categories = ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree']

# List of columns that need to be converted
columns_to_order = [
    "Ease and convenient", "Time saving", "More restaurant choices", "Easy Payment option",
    "More Offers and Discount", "Good Food quality", "Good Tracking system", "Self Cooking",
    "Late Delivery", "Poor Hygiene", "Unavailability",
    "Unaffordable", "Long delivery time", "Delay of delivery person getting assigned",
    "Wrong order delivered", "Missing item",
    "Order placed by mistake", "Residence in busy location"
]

# Apply categorical ordering to each column
for col in columns_to_order:
    df_copy[col] = pd.Categorical(df_copy[col], categories=ordered_categories, ordered=True)

# Verify changes
#print(df_copy.dtypes)  # Check the data types to confirm categorical conversion
df_copy[col]

0         Agree
1           NaN
2         Agree
3      Disagree
4         Agree
         ...   
383    Disagree
384       Agree
385       Agree
386         NaN
387       Agree
Name: Residence in busy location, Length: 388, dtype: category
Categories (5, object): ['Strongly disagree' < 'Disagree' < 'Neutral' < 'Agree' < 'Strongly agree']

In [ ]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
columns_to_order = [
    "Ease and convenient", "Time saving", "More restaurant choices", "Easy Payment option",
    "More Offers and Discount", "Good Food quality", "Good Tracking system", "Self Cooking",
    "Late Delivery", "Poor Hygiene", "Unavailability",
    "Unaffordable", "Long delivery time", "Delay of delivery person getting assigned",
    "Wrong order delivered", "Missing item",
    "Order placed by mistake", "Residence in busy location"
]

# Apply categorical ordering to each column
for col in columns_to_order:
   df_copy[col] = label.fit_transform(df_copy[col])

In [7]:
# Define the order of categories
ordered_categories = ['Unimportant', 'Slightly Important', 'Moderately Important', 'Important', 'Very Important']

# List of columns that need to be converted
columns_to_order = [
    "Less Delivery time", "High Quality of package", "Politeness",
    "Freshness ", "Temperature", "Good Taste ", "Good Quantity"
]

# Apply categorical ordering to each column
for col in columns_to_order:
    df_copy[col] = pd.Categorical(df_copy[col], categories=ordered_categories, ordered=True)

# Verify changes
#print(df_copy.dtypes)  # Check the data types to confirm categorical conversion
df_copy[col]

0      Moderately Important
1            Very Important
2      Moderately Important
3                 Important
4            Very Important
               ...         
383               Important
384          Very Important
385          Very Important
386          Very Important
387      Slightly Important
Name: Good Quantity, Length: 388, dtype: category
Categories (5, object): ['Unimportant' < 'Slightly Important' < 'Moderately Important' < 'Important' <
                         'Very Important']

In [8]:
#from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
columns_to_order = [
    "Less Delivery time", "High Quality of package", "Politeness",
    "Freshness ", "Temperature", "Good Taste ", "Good Quantity"
]

# Apply categorical ordering to each column
for col in columns_to_order:
   df_copy[col] = label.fit_transform(df_copy[col])

In [9]:
# Define the order of categories
ordered_categories = ["15 minutes", "30 minutes", "45 minutes", "60 minutes", "More than 60 minutes"]

# List of columns that need to be converted
columns_to_order = [
    "Maximum wait time"
]

# Apply categorical ordering to each column
for col in columns_to_order:
    df_copy[col] = pd.Categorical(df_copy[col], categories=ordered_categories, ordered=True)

# Verify changes
#print(df_copy.dtypes)  # Check the data types to confirm categorical conversion
df_copy[col]

0      30 minutes
1      30 minutes
2      45 minutes
3      30 minutes
4      30 minutes
          ...    
383    30 minutes
384    45 minutes
385    45 minutes
386    45 minutes
387    30 minutes
Name: Maximum wait time, Length: 388, dtype: category
Categories (5, object): ['15 minutes' < '30 minutes' < '45 minutes' < '60 minutes' <
                         'More than 60 minutes']

In [10]:
from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
columns_to_order = [
    "Maximum wait time"
]

# Apply categorical ordering to each column
for col in columns_to_order:
   df_copy[col] = label.fit_transform(df_copy[col])

In [19]:
categorical_columns = ['Influence of time', 'Influence of rating', 'Order Time']
df_copy = pd.get_dummies(data=df_copy, columns=categorical_columns)

In [12]:
df_copy['Output'] = df_copy['Output'].astype('category').cat.codes
df_copy['Output']

0      1
1      1
2      1
3      1
4      1
      ..
383    1
384    1
385    1
386    1
387    1
Name: Output, Length: 388, dtype: int8

In [21]:
# Replace 'Prefer not to say' with 'Single' in the 'Marital Status' column
df_copy['Marital Status'] = df_copy['Marital Status'].replace('Prefer not to say', 'Single')

In [23]:
df_copy['Occupation'] = df_copy['Occupation'].replace('Self Employeed', 'Employee')

In [25]:
categorical_columns = ['Marital Status', 'Occupation']
df_copy = pd.get_dummies(data=df_copy, columns=categorical_columns)

In [27]:
# Define the age bins and corresponding labels
age_bins = [0, 18, 24, 34, 44, float('inf')]  # The upper limit is infinity for ages 45+
age_labels = ['Under 18', '18-24', '25-34', '35-44', '45+']

# Create a new 'Age Category' column based on the defined bins
df_copy['Age Category'] = pd.cut(df_copy['Age'], bins=age_bins, labels=age_labels, right=False)

# Display the updated DataFrame
print(df_copy[['Age', 'Age Category']].head())

   Age Age Category
0   20        18-24
1   24        25-34
2   22        18-24
3   22        18-24
4   22        18-24


In [29]:
df_copy.drop(['Age'], axis='columns', inplace=True)

In [30]:
# Label encoding (ordinal encoding)
df_copy['Age Category'] = df_copy['Age Category'].cat.codes

In [32]:
categorical_columns = ['Gender']
df_copy = pd.get_dummies(data=df_copy, columns=categorical_columns, drop_first=True)

In [34]:
categorical_columns = ['Meal(P1)']
df_copy = pd.get_dummies(data=df_copy, columns=categorical_columns)

In [35]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Ease and convenient                        388 non-null    int64
 1   Time saving                                388 non-null    int64
 2   More restaurant choices                    388 non-null    int64
 3   Easy Payment option                        388 non-null    int64
 4   More Offers and Discount                   388 non-null    int64
 5   Good Food quality                          388 non-null    int64
 6   Good Tracking system                       388 non-null    int64
 7   Self Cooking                               388 non-null    int64
 8   Late Delivery                              388 non-null    int64
 9   Poor Hygiene                               388 non-null    int64
 10  Unavailability                             388 non

In [36]:
from sklearn.model_selection import train_test_split

x = df_copy.drop('Output',axis=1) # Independent variable
y = df_copy['Output'] # Dependent variable

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=23)

print('Training dataset size:', x_train.shape[0])
print('Testing dataset size:', x_test.shape[0])

Training dataset size: 291
Testing dataset size: 97


In [37]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [38]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

clf = DecisionTreeClassifier(random_state=42)
# since we have a relatively small dataset (~1000 records),
# we'll use a low number of splits
skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(clf, x_train, y_train, cv=skf, scoring='accuracy')
scores

array([0.76666667, 0.86206897, 0.93103448, 0.89655172, 0.86206897,
       0.89655172, 0.93103448, 0.86206897, 0.82758621, 0.89655172])

In [39]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = clf.predict(x_train)
        clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf.predict(x_test)
        clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

In [40]:
print_score(tree_clf, x_train, y_train, x_test, y_test, train=True)
print_score(tree_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    63.0  228.0       1.0      291.0         291.0
_______________________________________________
Confusion Matrix: 
 [[ 63   0]
 [  0 228]]

Test Result:
Accuracy Score: 81.44%
_______________________________________________
CLASSIFICATION REPORT:
                0          1  accuracy  macro avg  weighted avg
precision   0.625   0.876712  0.814433   0.750856      0.814433
recall      0.625   0.876712  0.814433   0.750856      0.814433
f1-score    0.625   0.876712  0.814433   0.750856      0.814433
support    24.000  73.000000  0.814433  97.000000     97.000000
_______________________________________________
Confusion Matrix: 
 [[15  9]
 [ 9 

In [41]:
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100)
rf_clf.fit(x_train, y_train)

print_score(rf_clf, x_train, y_train, x_test, y_test, train=True)
print_score(rf_clf, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    63.0  228.0       1.0      291.0         291.0
_______________________________________________
Confusion Matrix: 
 [[ 63   0]
 [  0 228]]

Test Result:
Accuracy Score: 86.60%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.823529   0.875000  0.865979   0.849265      0.862265
recall      0.583333   0.958904  0.865979   0.771119      0.865979
f1-score    0.682927   0.915033  0.865979   0.798980      0.857604
support    24.000000  73.000000  0.865979  97.000000     97.000000
_______________________________________________
Confusion Matrix: 


In [42]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

print_score(knn, x_train, y_train, x_test, y_test, train=True)
print_score(knn, x_train, y_train, x_test, y_test, train=False)


Train Result:
Accuracy Score: 86.25%
_______________________________________________
CLASSIFICATION REPORT:
                   0           1  accuracy   macro avg  weighted avg
precision   0.767442    0.879032  0.862543    0.823237      0.854874
recall      0.523810    0.956140  0.862543    0.739975      0.862543
f1-score    0.622642    0.915966  0.862543    0.769304      0.852463
support    63.000000  228.000000  0.862543  291.000000    291.000000
_______________________________________________
Confusion Matrix: 
 [[ 33  30]
 [ 10 218]]

Test Result:
Accuracy Score: 71.13%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.357143   0.771084   0.71134   0.564114      0.668666
recall      0.208333   0.876712   0.71134   0.542523      0.711340
f1-score    0.263158   0.820513   0.71134   0.541835      0.682611
support    24.000000  73.000000   0.71134  97.000000     97.000000
_____________