<a href="https://colab.research.google.com/github/mayamoneib/deliveryfood/blob/main/surveydata.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#%matplotlib inline
#plt.style.use("seaborn")
#when using colab
# Set the style for plots using the updated seaborn style
plt.style.use("seaborn-v0_8") # Changed from 'seaborn' to 'seaborn-v0_8'

df = pd.read_csv('Egypt Survey Data.csv.zip')

In [4]:

df_copy = df.copy()
df_copy.head()

Timestamp What is your preferred meal type to order?  \
0  2025/03/24 11:46:09 pm EET                                      Lunch   
1  2025/03/24 11:50:17 pm EET                                      Lunch   
2  2025/03/24 11:54:08 pm EET                                      Lunch   
3  2025/03/24 11:55:31 pm EET                                      Lunch   
4  2025/03/24 11:56:36 pm EET                                      Lunch   

  What is your preferred time to order?    \
0                                 Weekend   
1                                 Anytime   
2                                Weekdays   
3                                 Anytime   
4                                 Weekend   

  How long are you willing to wait for food delivery?  \
0                                         45 minutes    
1                                         45 minutes    
2                                             1 hour    
3                                         45 minutes    
4                                         45 minutes    

  Do you consider restaurant reviews before ordering via delivery platforms?   \
0                                         Very Often                            
1                                          Sometimes                            
2                                          Sometimes                            
3                                          Sometimes                            
4                                         Very Often                            

  Do you prefer online food delivery over cooking at home?  \
0                                          Sometimes         
1                                         Very Often         
2                                          Sometimes         
3                                          Sometimes         
4                                         Very Often         

  App is user-friendly      Time-saving Offers high-quality products  \
0  Moderately Important       Important         Moderately Important   
1        Very Important  Very Important           Slightly Important   
2             Important       Important                    Important   
3             Important       Important                    Important   
4        Very Important  Very Important               Very Important   

  Offers tasty food products  ...  \
0                  Important  ...   
1                  Important  ...   
2                  Important  ...   
3                  Important  ...   
4             Very Important  ...   

  Delivery of food while maintaining its appropriate temperature   \
0                                          Important                
1                                 Slightly Important                
2                                     Very Important                
3                                     Very Important                
4                                     Very Important                

  Delivery of items in high-quality packaging  \
0                          Slightly Important   
1                        Moderately Important   
2                                   Important   
3                              Very Important   
4                              Very Important   

  Accurate delivery tracking system  Friendly delivery personnel   Age?  \
0                          Important        Moderately Important  18-24   
1                     Very Important               Not Important  18-24   
2               Moderately Important          Slightly Important  18-24   
3                          Important                   Important  18-24   
4                     Very Important              Very Important  18-24   

  Gender? Marital Status? Occupation?  \
0  Female          Single     Student   
1  Female          Single     Student   
2  Female          Single     Student   
3  Female          Single     Student   
4  Female          Single     Student   

  From what type of area 

In [ ]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 31 columns):
 #   Column                                                                                         Non-Null Count  Dtype 
---  ------                                                                                         --------------  ----- 
 0   Timestamp                                                                                      236 non-null    object
 1   What is your preferred meal type to order?                                                     236 non-null    object
 2   What is your preferred time to order?                                                          236 non-null    object
 3   How long are you willing to wait for food delivery?                                            236 non-null    object
 4   Do you consider restaurant reviews before ordering via delivery platforms?                     236 non-null    object
 5   Do you prefer online food del

In [5]:
df_copy.columns = [col.rstrip() for col in df_copy.columns]

In [6]:
df_copy = df_copy.rename(columns={'What is your preferred meal type to order?':'Meal Type',
                                  'What is your preferred time to order?':'Preferred Order Time',
                                  'How long are you willing to wait for food delivery?':'Max Wait Time',
                                  'Do you consider restaurant reviews before ordering via delivery platforms?':'Check Reviews Before Delivery',
                                  'Do you prefer online food delivery over cooking at home?':'Delivery over Cooking',
                                  'App is user-friendly':'Good App UI',
                                  'Offers high-quality products':'High-quality products',
                                  'Offers tasty food products':'Tasty Food',
                                  'Offers several food brands':'Many Food Brands',
                                  'Offers easy payment options':'Easy Payment', # This was missing
                                  'Offers promotions & discounts':'Offers Promotions', # This was missing
                                  'Insufficient delivery personnel during peak times leading to order cancellation':'Insufficient delivery personnel',
                                  'Missing items in the order':'Missing items',
                                  'Delivery of fresh food':'Fresh food',
                                  'Delivery of food while maintaining its appropriate temperature':'Appropriate temperature',
                                  'Delivery of items in high-quality packaging':'High-quality packaging',
                                  'Accurate delivery tracking system':'Accurate Tracking System',
                                  'Age?':'Age',
                                  'Gender?':'Gender',
                                  'Marital Status?':'Marital Status',
                                  'Occupation?':"Occupation",
                                  'From what type of area do you typically place your orders?':'Area Type',
                                  'Finally, do you think online food delivery platforms are the most convenient option nowadays?':"Purchase Decision"})

In [7]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 31 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Timestamp                        264 non-null    object
 1   Meal Type                        264 non-null    object
 2   Preferred Order Time             264 non-null    object
 3   Max Wait Time                    264 non-null    object
 4   Check Reviews Before Delivery    264 non-null    object
 5   Delivery over Cooking            264 non-null    object
 6   Good App UI                      264 non-null    object
 7   Time-saving                      264 non-null    object
 8   High-quality products            264 non-null    object
 9   Tasty Food                       264 non-null    object
 10  Many Food Brands                 264 non-null    object
 11  Easy Payment                     264 non-null    object
 12  Offers Promotions                264

In [8]:
df_copy.drop(columns=['Timestamp'], inplace=True)

In [9]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Meal Type                        264 non-null    object
 1   Preferred Order Time             264 non-null    object
 2   Max Wait Time                    264 non-null    object
 3   Check Reviews Before Delivery    264 non-null    object
 4   Delivery over Cooking            264 non-null    object
 5   Good App UI                      264 non-null    object
 6   Time-saving                      264 non-null    object
 7   High-quality products            264 non-null    object
 8   Tasty Food                       264 non-null    object
 9   Many Food Brands                 264 non-null    object
 10  Easy Payment                     264 non-null    object
 11  Offers Promotions                264 non-null    object
 12  Late Delivery                    264

In [11]:

from sklearn.preprocessing import LabelEncoder

label = LabelEncoder()
columns_to_order = [
    "Check Reviews Before Delivery", "Time-saving", "Delivery over Cooking", "Good App UI",
    "High-quality products", "Tasty Food", "Many Food Brands", "Easy Payment",
    "Late Delivery", "Poor Hygiene", "Offers Promotions",
    "Unavailable Demanded Items", "Unaffordable Prices", "Insufficient delivery personnel",
    "Wrong delivery order", "Missing items",
    "Accurate Tracking System", "Friendly delivery personnel", "Fresh food",
    "Appropriate temperature", "High-quality packaging", "Age", "Max Wait Time",
    "Area Type"
]

# Apply categorical ordering to each column
for col in columns_to_order:
   df_copy[col] = label.fit_transform(df_copy[col])

In [12]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Meal Type                        264 non-null    object
 1   Preferred Order Time             264 non-null    object
 2   Max Wait Time                    264 non-null    int64 
 3   Check Reviews Before Delivery    264 non-null    int64 
 4   Delivery over Cooking            264 non-null    int64 
 5   Good App UI                      264 non-null    int64 
 6   Time-saving                      264 non-null    int64 
 7   High-quality products            264 non-null    int64 
 8   Tasty Food                       264 non-null    int64 
 9   Many Food Brands                 264 non-null    int64 
 10  Easy Payment                     264 non-null    int64 
 11  Offers Promotions                264 non-null    int64 
 12  Late Delivery                    264

In [13]:
categorical_columns = ['Gender', 'Occupation', 'Marital Status', 'Preferred Order Time', 'Meal Type']
df_copy = pd.get_dummies(data=df_copy, columns=categorical_columns, drop_first=True)

In [14]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 35 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   Max Wait Time                    264 non-null    int64 
 1   Check Reviews Before Delivery    264 non-null    int64 
 2   Delivery over Cooking            264 non-null    int64 
 3   Good App UI                      264 non-null    int64 
 4   Time-saving                      264 non-null    int64 
 5   High-quality products            264 non-null    int64 
 6   Tasty Food                       264 non-null    int64 
 7   Many Food Brands                 264 non-null    int64 
 8   Easy Payment                     264 non-null    int64 
 9   Offers Promotions                264 non-null    int64 
 10  Late Delivery                    264 non-null    int64 
 11  Unavailable Demanded Items       264 non-null    int64 
 12  Unaffordable Prices              264

In [15]:
df_copy['Purchase Decision'] = df_copy['Purchase Decision'].astype('category').cat.codes
df_copy['Purchase Decision']

0      0
1      1
2      1
3      1
4      1
      ..
259    0
260    0
261    0
262    0
263    0
Name: Purchase Decision, Length: 264, dtype: int8

In [16]:
from sklearn.model_selection import train_test_split

x = df_copy.drop('Purchase Decision',axis=1) # Independent variable
y = df_copy['Purchase Decision'] # Dependent variable

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=23)

print('Training dataset size:', x_train.shape[0])
print('Testing dataset size:', x_test.shape[0])

Training dataset size: 198
Testing dataset size: 66


In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

clf1 = DecisionTreeClassifier(random_state=42)

# since we have a relatively small dataset (~1000 records),
# we'll use a low number of splits
skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(clf1, x_train, y_train, cv=skf, scoring='accuracy')

clf1.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [18]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score(clf1, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = clf1.predict(x_train)
        clf1_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf1_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = clf1.predict(x_test)
        clf1_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{clf1_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print_score(clf1, x_train, y_train, x_test, y_test, train=True)
print_score(clf1, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    39.0  159.0       1.0      198.0         198.0
_______________________________________________
Confusion Matrix: 
 [[ 39   0]
 [  0 159]]

Test Result:
Accuracy Score: 77.27%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.600000   0.823529  0.772727   0.711765      0.762567
recall      0.500000   0.875000  0.772727   0.687500      0.772727
f1-score    0.545455   0.848485  0.772727   0.696970      0.765840
support    18.000000  48.000000  0.772727  66.000000     66.000000
_______________________________________________
Confusion Matrix: 


In [19]:
from sklearn.ensemble import RandomForestClassifier

rf_clf2 = RandomForestClassifier(n_estimators=100)


skf = StratifiedKFold(n_splits=10)
scores = cross_val_score(rf_clf2, x_train, y_train, cv=skf, scoring='accuracy')

rf_clf2.fit(x_train, y_train)
# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation

scores

array([0.8       , 0.85      , 0.85      , 0.85      , 0.85      ,
       0.9       , 0.85      , 0.85      , 0.89473684, 0.78947368])

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score1(rf_clf2, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = rf_clf2.predict(x_train)
        rf_clf2_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{rf_clf2_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = rf_clf2.predict(x_test)
        rf_clf2_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{rf_clf2_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print_score1(rf_clf2, x_train, y_train, x_test, y_test, train=True)
print_score1(rf_clf2, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    39.0  159.0       1.0      198.0         198.0
_______________________________________________
Confusion Matrix: 
 [[ 39   0]
 [  0 159]]

Test Result:
Accuracy Score: 86.36%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.909091   0.854545  0.863636   0.881818      0.869421
recall      0.555556   0.979167  0.863636   0.767361      0.863636
f1-score    0.689655   0.912621  0.863636   0.801138      0.851812
support    18.000000  48.000000  0.863636  66.000000     66.000000
_______________________________________________
Confusion Matrix: 


In [21]:

from sklearn.neighbors import KNeighborsClassifier

knn2 = KNeighborsClassifier(n_neighbors=5)


skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(knn2, x_train, y_train, cv=skf, scoring='accuracy')

knn2.fit(x_train, y_train)

print_score(knn2, x_train, y_train, x_test, y_test, train=True)
print_score(knn2, x_train, y_train, x_test, y_test, train=False)

Train Result:
Accuracy Score: 87.88%
_______________________________________________
CLASSIFICATION REPORT:
                   0           1  accuracy   macro avg  weighted avg
precision   0.777778    0.894737  0.878788    0.836257      0.871699
recall      0.538462    0.962264  0.878788    0.750363      0.878788
f1-score    0.636364    0.927273  0.878788    0.781818      0.869972
support    39.000000  159.000000  0.878788  198.000000    198.000000
_______________________________________________
Confusion Matrix: 
 [[ 21  18]
 [  6 153]]

Test Result:
Accuracy Score: 83.33%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.818182   0.836364  0.833333   0.827273      0.831405
recall      0.500000   0.958333  0.833333   0.729167      0.833333
f1-score    0.620690   0.893204  0.833333   0.756947      0.818882
support    18.000000  48.000000  0.833333  66.000000     66.000000
_____________

In [22]:

from sklearn.ensemble import GradientBoostingClassifier

gbm_clf = GradientBoostingClassifier()

skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(gbm_clf, x_train, y_train, cv=skf, scoring='accuracy')

gbm_clf.fit(x_train, y_train)

GradientBoostingClassifier()

In [23]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score3(gbm_clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = gbm_clf.predict(x_train)
        gbm_clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{gbm_clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = gbm_clf.predict(x_test)
        gbm_clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{gbm_clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print("thsi is gbmmm")
print_score3(gbm_clf, x_train, y_train, x_test, y_test, train=True)
print_score3(gbm_clf, x_train, y_train, x_test, y_test, train=False)

thsi is gbmmm
Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    39.0  159.0       1.0      198.0         198.0
_______________________________________________
Confusion Matrix: 
 [[ 39   0]
 [  0 159]]

Test Result:
Accuracy Score: 86.36%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.764706   0.897959  0.863636   0.831333      0.861617
recall      0.722222   0.916667  0.863636   0.819444      0.863636
f1-score    0.742857   0.907216  0.863636   0.825037      0.862391
support    18.000000  48.000000  0.863636  66.000000     66.000000
_______________________________________________
Confu

In [24]:

from sklearn.svm import SVC

svm_clf = SVC()

skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(svm_clf, x_train, y_train, cv=skf, scoring='accuracy')

svm_clf.fit(x_train, y_train)

SVC()

In [25]:

#from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score5(svm_clf, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = svm_clf.predict(x_train)
        svm_clf_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{svm_clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = svm_clf.predict(x_test)
        svm_clf_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{svm_clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print("thsi is svmmm")
print_score5(svm_clf, x_train, y_train, x_test, y_test, train=True)
print_score5(svm_clf, x_train, y_train, x_test, y_test, train=False)#

thsi is svmmm
Train Result:
Accuracy Score: 87.37%
_______________________________________________
CLASSIFICATION REPORT:
                   0           1  accuracy   macro avg  weighted avg
precision   1.000000    0.864130  0.873737    0.932065      0.890893
recall      0.358974    1.000000  0.873737    0.679487      0.873737
f1-score    0.528302    0.927114  0.873737    0.727708      0.848560
support    39.000000  159.000000  0.873737  198.000000    198.000000
_______________________________________________
Confusion Matrix: 
 [[ 14  25]
 [  0 159]]

Test Result:
Accuracy Score: 77.27%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   1.000000   0.761905  0.772727   0.880952      0.826840
recall      0.166667   1.000000  0.772727   0.583333      0.772727
f1-score    0.285714   0.864865  0.772727   0.575290      0.706915
support    18.000000  48.000000  0.772727  66.000000     66.000000

In [26]:
from sklearn.linear_model import LogisticRegression

los_reg = LogisticRegression()

skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(los_reg, x_train, y_train, cv=skf, scoring='accuracy')

los_reg.fit(x_train, y_train);

In [27]:
#from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

def print_score7(los_reg, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = los_reg.predict(x_train)
        los_reg_report = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{los_reg_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = los_reg.predict(x_test)
        los_reg_report = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{los_reg_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print("thsi is losss")
print_score7(los_reg, x_train, y_train, x_test, y_test, train=True)
print_score7(los_reg, x_train, y_train, x_test, y_test, train=False)#

thsi is losss
Train Result:
Accuracy Score: 88.89%
_______________________________________________
CLASSIFICATION REPORT:
                   0           1  accuracy   macro avg  weighted avg
precision   0.869565    0.891429  0.888889    0.880497      0.887122
recall      0.512821    0.981132  0.888889    0.746976      0.888889
f1-score    0.645161    0.934132  0.888889    0.789647      0.877213
support    39.000000  159.000000  0.888889  198.000000    198.000000
_______________________________________________
Confusion Matrix: 
 [[ 20  19]
 [  3 156]]

Test Result:
Accuracy Score: 78.79%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.666667   0.814815  0.787879   0.740741      0.774411
recall      0.444444   0.916667  0.787879   0.680556      0.787879
f1-score    0.533333   0.862745  0.787879   0.698039      0.772906
support    18.000000  48.000000  0.787879  66.000000     66.000000

In [33]:
from sklearn.cluster import KMeans

km1 = KMeans(n_clusters=5, init='k-means++', max_iter=300, n_init=10, random_state=0)


skf = StratifiedKFold(n_splits=10)

# Note how cross validation is applied on the training dataset
# The testing dataset is always left out and used -only- in the final evaluation
scores = cross_val_score(km1, x_train, y_train, cv=skf, scoring='accuracy')

km1.fit(x_train, y_train)

KMeans(n_clusters=5, n_init=10, random_state=0)

In [34]:

def print_score9(km1, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = km1.predict(x_train)
        km_report1 = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{km_report1}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = km1.predict(x_test)
        km_report1 = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{km_report1}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print_score9(km1, x_train, y_train, x_test, y_test, train=True)
print_score9(km1, x_train, y_train, x_test, y_test, train=False)#

Train Result:
Accuracy Score: 13.13%
_______________________________________________
CLASSIFICATION REPORT:
                   0           1    2    3    4  accuracy   macro avg  \
precision   0.073171    0.884615  0.0  0.0  0.0  0.131313    0.191557   
recall      0.076923    0.144654  0.0  0.0  0.0  0.131313    0.044315   
f1-score    0.075000    0.248649  0.0  0.0  0.0  0.131313    0.064730   
support    39.000000  159.000000  0.0  0.0  0.0  0.131313  198.000000   

           weighted avg  
precision      0.724785  
recall         0.131313  
f1-score       0.214445  
support      198.000000  
_______________________________________________
Confusion Matrix: 
 [[ 3  3 24  4  5]
 [38 23 35 29 34]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]

Test Result:
Accuracy Score: 12.12%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1    2    3    4  accuracy  macro avg  \
precision   0.142857   0.777778  0.0  0.0  0.0  0.121212  

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.p

In [31]:
from xgboost import XGBClassifier

# Initialize the XGBoost model
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=0)

# Define Stratified K-Fold
skf = StratifiedKFold(n_splits=10)

# Apply cross-validation on the training set
scores = cross_val_score(xgb_model, x_train, y_train, cv=skf, scoring='accuracy')


# Fit the model to the full training set
xgb_model.fit(x_train, y_train)

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [20:00:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [20:00:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [20:00:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [20:00:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)
/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [20:00:28] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_e

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=0, ...)

In [35]:
def print_score10(xgb_model, x_train, y_train, x_test, y_test, train=True):
    if train:
        pred = xgb_model.predict(x_train)
        xgb_report1 = pd.DataFrame(classification_report(y_train, pred, output_dict=True))
        print("Train Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_train, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{xgb_report1}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, pred)}\n")

    elif train==False:
        pred = xgb_model.predict(x_test)
        xgb_report1 = pd.DataFrame(classification_report(y_test, pred, output_dict=True))
        print("Test Result:")
        print("===============================================")
        print(f"Accuracy Score: {accuracy_score(y_test, pred) * 100:.2f}%")
        print("_______________________________________________")
        print(f"CLASSIFICATION REPORT:\n{xgb_report1}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_test, pred)}\n")

print_score10(xgb_model, x_train, y_train, x_test, y_test, train=True)
print_score10(xgb_model, x_train, y_train, x_test, y_test, train=False)#

Train Result:
Accuracy Score: 100.00%
_______________________________________________
CLASSIFICATION REPORT:
              0      1  accuracy  macro avg  weighted avg
precision   1.0    1.0       1.0        1.0           1.0
recall      1.0    1.0       1.0        1.0           1.0
f1-score    1.0    1.0       1.0        1.0           1.0
support    39.0  159.0       1.0      198.0         198.0
_______________________________________________
Confusion Matrix: 
 [[ 39   0]
 [  0 159]]

Test Result:
Accuracy Score: 87.88%
_______________________________________________
CLASSIFICATION REPORT:
                   0          1  accuracy  macro avg  weighted avg
precision   0.857143   0.884615  0.878788   0.870879      0.877123
recall      0.666667   0.958333  0.878788   0.812500      0.878788
f1-score    0.750000   0.920000  0.878788   0.835000      0.873636
support    18.000000  48.000000  0.878788  66.000000     66.000000
_______________________________________________
Confusion Matrix: 
